update: Add note about SLA and prepare for GA
aiven/aiven-docs pull request #100
Opened 2024-03-04 14:44 UTC by harshini-rangaswamy

## Describe your changes
Added note to Dragonfly documentation advising customers to run a PoC with Aiven for Dragonfly before full production deployment. Removed LA tags for GA.
[MA-2419](https://aiven.atlassian.net/browse/MA-2419)
## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-03-05 14:20 UTC, safa-topal approved these changes
Lgtm

2024-03-05 15:28 UTC, hoang-vo approved these changes

2024-03-05 17:24 UTC, ArthurFlag requested changes
minor suggestion for maintenance

2024-03-05 17:24 UTC, ArthurFlag commented on docs/products/dragonfly/howto/migrate-aiven-redis-df-console.md
> +:::
This is repeated 3 times, so let's make it a reusable snippet to keep things clean?

1. Dump the note in `/static/includes/Dragonfly-SLA.md` or similar.
2. Import it where needed:
 
```
import Note from "@site/static/includes/Dragonfly-SLA.md"

<Note/>
```

2024-03-07 16:00 UTC, ArthurFlag approved these changes
Thank you!

2024-03-08 10:41 UTC, merged