update: project role permissions
aiven/aiven-docs pull request #135
Opened 2024-03-26 09:59 UTC by staceysalamon-aiven

## Describe your changes
Fix project member role descriptions.

## Checklist

- [X] The first paragraph of the page is on one line.
- [X] The other lines have a line break at 90 characters.
- [X] I checked the output.
- [X] I applied the [style guide](../styleguide.md).
- [X] My links start with `/docs/`.

2024-03-27 07:51 UTC, rsalevsky approved these changes

2024-03-27 16:51 UTC, ArthurFlag requested changes

2024-03-27 16:51 UTC, ArthurFlag commented on docs/platform/reference/project-member-privileges.md
> +  -   users who create a project.
```suggestion
  -   Every project has at least one admin user. This role is automatically granted to
      users who create a project.
```

2024-03-28 12:23 UTC, ArthurFlag approved these changes

2024-04-03 11:04 UTC, merged