add(postgresql): expose pgbouncer stats to datadog
aiven/aiven-docs pull request #146
Opened 2024-04-03 11:13 UTC by wojcik-dorota

## Describe your changes

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-04-03 12:58 UTC, 0xlianhu reviewed
It looks good to me.

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/monitor-database-with-datadog.md
> +- [Expose PgBouncer statistics to Datadog](/docs/products/postgresql/howto/pgbouncer-stats-datadog).
I recommend "PgBouncer monitoring with Datadog" analogous to our "Database monitoring with Datadog".

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/monitor-database-with-datadog.md
> +  [Datadog Deep Database Monitoring](https://www.datadoghq.com/product/database-monitoring/)
This is a minor thing but Datadog dropped the term "Deep" from their offering name (it is only visible in the main page headline but not referred to in any other place) so I recommend changing this to "Database monitoring with Datadog" to keep in line with the title of our own doc (https://aiven.io/docs/products/postgresql/howto/monitor-database-with-datadog).

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +title: Expose PgBouncer statistics to Datadog
I recommend "PgBouncer monitoring with Datadog"

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +sidebar_label: PgBouncer stats in Datadog
I recommend "PgBouncer monitoring with Datadog".

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +Connect PgBouncer with Datadog to display [PgBouncer statistics](/docs/products/postgresql/howto/pgbouncer-stats) on the Datadog platform.
I recommend "Integrate/Connect PgBouncer with Datadog to track connection pool metrics, and monitor application traffic on the Datadog platform".

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +## Expose PgBouncer statistics
I recommend "Enable monitoring" to drop the term "statistics" as well as to keep it consistent with "Enable monitoring" in [Database monitoring with Datadog :: Enable monitoring](https://aiven.io/docs/products/postgresql/howto/monitor-database-with-datadog#enable-monitoring)

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +You can expose PgBouncer statistics for your Aiven for PostgreSQL service both if the
I recommend to drop the terms "expose" and "statistics" in favor of "metrics" and "monitoring". I recommend the opening similar/consistent to the one in Database monitoring: "To use Datadog PgBouncer Monitoring with your Aiven for PostgreSQL® services, ...".

I am also not clear about the "regardless if this service already has a Datadog Metrics integration or not." part. Then, this begs the question of why Datadog metrics integration is a prerequise in the first place.
@0xlianhu could you please clarify?

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +### Expose PgBouncer stats if the integration exists
I suggest to drop the "expose" wording or this subsection title altogether analogous to [Database monitoring with Datadog :: Enable monitoring](https://aiven.io/docs/products/postgresql/howto/monitor-database-with-datadog#enable-monitoring).

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +1. To enable PgBouncer statistics in Datadog, set up the ``datadog_pgbouncer_enabled``
I recommend dropping "statistic" or using something like "... PgBouncer monitoring ...".

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +### Create the integration and expose PgBouncer stats
I recommend dropping the second part with the term "expose".
"Create the integration"

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto/pgbouncer-stats-datadog.md
> +and enable PgBouncer statistics in Datadog by running:
I recommend replacing "statistics" with "monitoring".

2024-04-03 13:28 UTC, divdby0 commented on sidebars.ts
> +                    'products/postgresql/howto/pgbouncer-stats-datadog',
I recommend the URI "pgbouncer-datadog" or "monitor-pgbouncer-with-datadog".

2024-04-03 13:28 UTC, divdby0 commented on docs/integrations/datadog/datadog-metrics.md
> +- [Expose PgBouncer statistics to Datadog](/docs/products/postgresql/howto/pgbouncer-stats-datadog).
I recommend "[PgBouncer monitoring with Datadog](/docs/products/postgresql/howto/monitor-pgbouncer-with-datadog)".

2024-04-03 13:28 UTC, divdby0 commented on docs/products/postgresql/howto.md
> +-   [PgBouncer statistics in Datadog](/docs/products/postgresql/howto/pgbouncer-stats-datadog)
I recommend "[PgBouncer monitoring with Datadog](/docs/products/postgresql/howto/monitor-pgbouncer-with-datadog)".

2024-04-15 15:23 UTC, divdby0 approved these changes

2024-04-16 08:51 UTC, ArthurFlag requested changes
minor md syntax comments

2024-04-16 08:51 UTC, ArthurFlag commented on docs/products/postgresql/howto/monitor-pgbouncer-with-datadog.md
> +1. Obtain the SERVICE_INTEGRATION_ID of the Datadog Metrics integration for your Aiven for
Can we put variable names as inline code to help with scanability (applies to the whole file)?

```suggestion
1. Obtain the `SERVICE_INTEGRATION_ID` of the Datadog Metrics integration for your Aiven for
```

2024-04-16 08:51 UTC, ArthurFlag commented on docs/products/postgresql/howto/monitor-pgbouncer-with-datadog.md
> +   parameter to ``true``:
Applies to the whole file: only one backtick for inline code in MD :) 

```suggestion
1. To enable PgBouncer monitoring in Datadog, set up the `datadog_pgbouncer_enabled`
   parameter to `true`:
```

2024-04-18 07:46 UTC, merged