cloud support
aiven/aiven-docs pull request #198
Opened 2024-05-14 14:53 UTC by wojcik-dorota

## Describe your changes

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-05-14 15:48 UTC, ArthurAnsquer requested changes

2024-05-14 15:48 UTC, ArthurAnsquer commented on docs/products/clickhouse/howto/enable-tiered-storage.md
> +-   You can enable tiered storage in an Aiven for ClickHouse service if it is hosted on
Here with this phrasing I'd say "in a non-BYOC" or "on Aiven tenant" WDYT?

2024-05-14 15:48 UTC, ArthurAnsquer commented on docs/products/clickhouse/concepts/clickhouse-tiered-storage.md
> +-   You can enable tiered storage in an Aiven for ClickHouse service if it is hosted on
Here with this phrasing I'd say "in a non-BYOC" or "on Aiven tenant" WDYT?

2024-05-21 07:46 UTC, ArthurAnsquer approved these changes

2024-05-22 11:53 UTC, ArthurFlag approved these changes

2024-05-22 11:56 UTC, merged