feat: required access snippet
aiven/aiven-docs pull request #20
Opened 2024-01-31 10:51 UTC by staceysalamon-aiven

## Describe your changes
Adds a snippet for inserting a section into docs indicating what permissions are needed to access a feature.

2024-01-31 14:39 UTC, ArthurFlageul requested changes

2024-01-31 14:39 UTC, ArthurFlageul commented on .vscode/aiven.code-snippets
> +      "## Required access",
Nice to see you're looking into snippets 👌  

As far as the content goes, we should do our best not to duplicate titles, so we don't end up with many identical H2 by design and negatively impact SEO. Maybe this should be an admonition?

2024-01-31 14:45 UTC, ArthurFlageul commented on .vscode/aiven.code-snippets
> +      "## Required access",
I also realize we certainly did this for the related links bit but I'll modify it to not make it a _real_ h2.

2024-02-01 09:03 UTC, staceysalamon-aiven commented
@ArthurFlageul Made the changes, but Cloudflare is now complaining about a bunch of broken links. 🤔

2024-02-01 09:56 UTC, merged