Updated the 'request a new extension' section
aiven/aiven-docs pull request #208
Opened 2024-05-16 04:58 UTC by joshuabeckett

## Describe your changes
I updated the [documentation](https://aiven.io/docs/products/postgresql/howto/manage-extensions#request-a-new-extension) that stated how to request a new extension, to be more accurate. The customer should do this through the Ideas Portal, not create a support ticket, since we just divert them to that anyway

JIRA ticket
https://aiven.atlassian.net/browse/SRE-8655

2024-05-16 08:46 UTC, staceysalamon-aiven approved these changes
Thank you for updating this! I just made a minor change to use the name of the site, Aiven Ideas, and reworded this slightly to fit with our style guide. :)

2024-05-16 08:46 UTC, staceysalamon-aiven commented on docs/products/postgresql/howto/manage-extensions.md
> +[Extensions on Aiven for PostgreSQL®](/docs/products/postgresql/reference/list-of-extensions) approved list, please make a request through our [Ideas Portal](https://ideas.aiven.io//). Be sure to inc
```suggestion
[list of approved extensions](/docs/products/postgresql/reference/list-of-extensions), make a request through [Aiven Ideas](https://ideas.aiven.io/). Be sure to include:
```

2024-05-16 08:48 UTC, staceysalamon-aiven requested changes

2024-05-16 08:48 UTC, staceysalamon-aiven commented on docs/products/postgresql/howto/manage-extensions.md
> +[Extensions on Aiven for PostgreSQL®](/docs/products/postgresql/reference/list-of-extensions) approved list, please make a request through our [Ideas Portal](https://ideas.aiven.io//). Be sure to inc
```suggestion
[list of approved extensions](/docs/products/postgresql/reference/list-of-extensions), make a request through [Aiven Ideas](https://ideas.aiven.io/). Be sure to include:
```

2024-05-28 20:57 UTC, joshuabeckett reviewed
LGTM!

2024-05-29 08:07 UTC, staceysalamon-aiven approved these changes

2024-05-29 08:07 UTC, merged