Dorota clickhouse tiered storage updates
aiven/aiven-docs pull request #231
Opened 2024-05-31 13:27 UTC by wojcik-dorota

## Describe your changes

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-06-17 09:18 UTC, ArthurAnsquer approved these changes

2024-06-17 10:08 UTC, ArthurFlag requested changes

2024-06-17 10:08 UTC, ArthurFlag commented on docs/products/clickhouse/concepts/clickhouse-tiered-storage.md
> +      **Storage details**
I really advise caution about this "micro docs" inside a given doc. The day we touch up the UI to move a section, it'll be very hard to update all these little procedures. Ideally, we really want something like: 

> ... between your Clickhouse [Tiered storage]() and [Storage details]().

If ppl have no clue what these are and how to display these views, they just click on the links. 
This also helps us lighten up the content and ensure a pattern in each feature such as having a task to display tiered storage, storage details, and the rest.
For example, this reveals we should perhaps have a section to explain and display tierd storage in https://aiven.io/docs/products/clickhouse/howto/list-tiered-storage?

2024-06-17 10:08 UTC, ArthurFlag commented on docs/products/clickhouse/concepts/clickhouse-tiered-storage.md
> +      **Databases and tables** > **Storage details** of your table.
Same comment here, we want to reuse content with a pattern like:

```suggestion
      To check if you successfully transferred data to object storage, display the [Storage data]() of the table.
```

2024-06-18 10:30 UTC, ArthurFlag approved these changes
Thanks for the update 🙌

2024-06-18 11:07 UTC, merged