update: teams migration guides deprecation info
aiven/aiven-docs pull request #247
Opened 2024-06-06 06:50 UTC by staceysalamon-aiven

## Describe your changes

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-06-10 12:55 UTC, staceysalamon-aiven commented
Preview of teams page: https://staceys-teams-deprecation-eh.aiven-docs.pages.dev/docs/tools/aiven-console/howto/create-manage-teams

Terraform migration guide: https://staceys-teams-deprecation-eh.aiven-docs.pages.dev/docs/tools/terraform/howto/migrate-from-teams-to-groups

2024-06-13 08:42 UTC, ArthurFlag commented on docs/tools/terraform/howto/migrate-from-teams-to-groups.md
> +    have full access to organizations.
Nitpick: the indent is 2 spaces too large for the list paragraphs. Not too bad to fix with multiline select in VSCode. 

```suggestion
    The Account Owners and super admin
    are synced, so the removal of the Account Owners team will have no impact on your
    operations. [Super admin](/docs/platform/concepts/orgs-units-projects#users-and-roles)
    have full access to organizations.
```

2024-07-01 10:10 UTC, rsalevsky requested changes

2024-07-01 10:10 UTC, rsalevsky commented on docs/tools/aiven-console/howto/create-manage-teams.md
> +will disable the teams feature. You won't be able to create new teams or access your
Let's make this bold to increase visibility.

2024-07-01 10:14 UTC, rsalevsky approved these changes

2024-07-01 10:29 UTC, merged