fix: information about persistence for Caching service backup
aiven/aiven-docs pull request #275
Opened 2024-06-17 12:22 UTC by harshini-rangaswamy

## Describe your changes

This pull request updates docs to reflect the current behavior of Redis Persistence, specifically regarding the deletion of all existing backups when persistence is switched off.

[DOC-1023](https://aiven.atlassian.net/browse/DOC-1023)

## Checklist

- [x] The first paragraph of the page is on one line.
- [x] The other lines have a line break at 90 characters.
- [x] I checked the output.
- [x] I applied the [style guide](../styleguide.md).
- [x] My links start with `/docs/`.

[DOC-1023]: https://aiven.atlassian.net/browse/DOC-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-20 14:30 UTC, bogdanp05 requested changes
The warning looks good.

2024-06-20 14:30 UTC, bogdanp05 commented on docs/platform/concepts/service_backups.md
> +  stops all Redis RDB dumps and backups If the service restarts or powers off for
`.` after "and backups".

2024-06-20 14:33 UTC, harshini-rangaswamy commented on docs/platform/concepts/service_backups.md
> +  stops all Redis RDB dumps and backups If the service restarts or powers off for
fixed

2024-06-20 14:39 UTC, bogdanp05 approved these changes

2024-06-21 10:02 UTC, wojcik-dorota approved these changes
One suggestion, otherwise LGTM :-)

2024-06-21 10:02 UTC, wojcik-dorota commented on docs/platform/concepts/service_backups.md
> +section on your **Service settings** page in the [Aiven Console](https://console.aiven.io).
nitpicking: you might include the cog icon for `**Service settings**`.

2024-06-21 11:52 UTC, merged