update(platform): add step to link verified domains to IdP
aiven/aiven-docs pull request #31
Opened 2024-02-05 10:31 UTC by staceysalamon-aiven

## Describe your changes
The option to link a verified domain is being added to the IdP wizard. 

## Checklist

- [X] The first paragraph of the page is on one line.
- [X] The other lines have a line break at 90 characters.
- [X] I checked the output.
- [X] I applied the [style guide](../styleguide.md).
- [X] My links start with `/docs/`.

2024-02-19 14:55 UTC, rsalevsky requested changes
We should also mention that linking a domain will make it possible for users from this domain to just login with the IdP.

2024-02-19 14:55 UTC, rsalevsky commented on docs/platform/howto/saml/add-identity-providers.md
> +1. Optional: Select a [verified domain](/docs/platform/howto/manage-domains) to link
Let's make it mandatory. :) Henri just started working on enforcing it.

2024-02-20 09:41 UTC, rsalevsky approved these changes

2024-02-21 11:49 UTC, harshini-rangaswamy approved these changes
LGTM

2024-02-21 13:02 UTC, ArthurFlag approved these changes

2024-02-21 13:04 UTC, merged