update(platform): pro labels for pro features
aiven/aiven-docs pull request #39
Opened 2024-02-07 13:28 UTC by wojcik-dorota

## Describe your changes

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-02-16 17:20 UTC, caydinavn approved these changes

2024-02-16 17:20 UTC, caydinavn commented on docs/platform/concepts/enhanced-compliance-env.md
> +If you require compliance beyond these, contact the [sales team](mailto:sales@aiven.io)
```suggestion
If you have other compliance requirements, contact the [sales team](mailto:sales@aiven.io)
```

2024-02-19 15:28 UTC, ArthurFlag requested changes

2024-02-19 15:28 UTC, ArthurFlag commented on docs/platform/howto/attach-vpc-aws-tgw.md
> +traffic to all other networks attached - directly or indirectly - to the Transit Gateway.
Could we avoid using dashes? If they can be replaced by commas, let's do so. These dashes are not meant for this kind of use, but only for compound nouns.

2024-02-20 13:54 UTC, ArthurFlag requested changes
minor typo and we're gtg

2024-02-20 13:54 UTC, ArthurFlag commented on docs/platform/howto/use-azure-privatelink.md
> +pro: ture
```suggestion
pro: true
```

2024-06-28 10:01 UTC, closed without merging