Update OpenSearch data migration prerequisite
aiven/aiven-docs pull request #496
Opened 2024-10-09 11:40 UTC by hoang-vo

## Describe your changes
Adding steps in the prerequisite to conduct data migration for OpenSearch 

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](styleguide.md).
- [ ] My links start with `/docs/`.

2024-10-09 12:55 UTC, staceysalamon-aiven requested changes
Thanks for doing this, @hoang-vo! I've reviewed in Harshini's absence, but I don't have all the background and I'm not 100% certain about the terminology.

2024-10-09 12:55 UTC, staceysalamon-aiven commented on docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
> +- Optional: If you want to verify the migration using our Script-based Validation
```suggestion
- Optional: To verify the migration using Aiven's script-based validation
```

2024-10-09 12:55 UTC, staceysalamon-aiven commented on docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
> +  below, you need to take the initial data of the source cluster into a json file
```suggestion
, put the initial data of the source cluster into a JSON file
```

2024-10-09 12:55 UTC, staceysalamon-aiven commented on docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
> +  before the data migration. Taking the data by running the
```suggestion
  before the data migration. Get the data by running the
```

2024-10-09 12:55 UTC, staceysalamon-aiven commented on docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
> +  `get_migration_validation_data.py` script from the [[Aiven examples GitHub repository](https://github.com/aiven/aiven-examples/blob/main/solutions/validate-elasticsearch-to-opensearch-migration/get
```suggestion
  `get_migration_validation_data.py` script from the [[Aiven examples GitHub repository](https://github.com/aiven/aiven-examples/blob/main/solutions/validate-elasticsearch-to-opensearch-migration/get_migration_validation_data.py):
```

2024-10-09 12:55 UTC, staceysalamon-aiven commented on docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
> +- Optiona: If you want to verify the migration using our Script-based Validation
Is this different from the migration validation steps above it? I see it includes the target cluster here, but it's not clear to me when you would use one over the other.

2024-10-11 08:12 UTC, harshini-rangaswamy commented
> Thanks for doing this, @hoang-vo! I've reviewed in Harshini's absence, but I don't have all the background and I'm not 100% certain about the terminology.

Thanks for reviewing this, @staceysalamon-aiven. I have moved the content into a subsection within the prerequisites and updated it to align with the rest of the document for consistency.

2024-10-11 13:28 UTC, harshini-rangaswamy approved these changes

2024-10-11 13:38 UTC, merged