update: use permission resource in teams migration
aiven/aiven-docs pull request #529
Opened 2024-10-25 13:46 UTC by staceysalamon-aiven

## Describe your changes

Updates teams to groups migration instructions to use the new `aiven_organization_permission` resource.

## Checklist

- [X] The first paragraph of the page is on one line.
- [X] The other lines have a line break at 90 characters.
- [X] I checked the output.
- [X] I applied the [style guide](styleguide.md).
- [X] My links start with `/docs/`.

2024-10-25 14:42 UTC, rriski approved these changes

2024-10-28 09:07 UTC, ArthurFlag requested changes

2024-10-28 09:07 UTC, ArthurFlag commented on docs/tools/terraform/howto/migrate-from-teams-to-groups.md
> +3.  To add the users to the groups, use the
Could you revert to `1.`'s?

2024-10-29 08:54 UTC, ArthurFlag approved these changes

2024-10-29 08:54 UTC, merged