add(cassandra): pro platform tag and prerequisite for CCR docs
aiven/aiven-docs pull request #54
Opened 2024-02-13 14:20 UTC by wojcik-dorota

https://aiven.atlassian.net/browse/DOC-837

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-03-11 11:17 UTC, ArthurAnsquer requested changes

2024-03-11 11:17 UTC, ArthurAnsquer commented on docs/products/cassandra/howto/disable-cross-cluster-replication.md
>      service on which you'd like to enable CCR.
This should say "to disable CCR" as this section is about disabling CCR by deleting services

2024-03-11 11:17 UTC, ArthurAnsquer commented on docs/products/cassandra/howto/disable-cross-cluster-replication.md
> +pro: true
Already raised it on slack, but just for being extra sure! Pro Platform is now Aiven Entreprise

2024-03-11 11:17 UTC, ArthurAnsquer commented on docs/products/cassandra/howto/enable-cross-cluster-replication.md
> +pro: true
Already raised it on slack, but just for being extra sure! Pro Platform is now Aiven Entreprise

2024-03-11 11:17 UTC, ArthurAnsquer commented on docs/products/cassandra/howto/list-cross-cluster-replication.md
> +pro: true
Already raised it on slack, but just for being extra sure! Pro Platform is now Aiven Entreprise

2024-03-11 11:17 UTC, ArthurAnsquer commented on docs/products/cassandra/howto/manage-cross-cluster-replication.md
> +pro: true
Already raised it on slack, but just for being extra sure! Pro Platform is now Aiven Entreprise

2024-03-11 11:17 UTC, ArthurAnsquer commented on docs/products/cassandra/concepts/cross-cluster-replication.md
> +pro: true
Already raised it on slack, but just for being extra sure! Pro Platform is now Aiven Entreprise

2024-03-11 11:17 UTC, ArthurAnsquer commented on docs/products/cassandra/howto/enable-cross-cluster-replication.md
> +1.  Verify your choices in the **Services summary** card on the right
I think formatting got strange and this should be "4." but got set automatically to "1."

2024-03-11 15:57 UTC, ArthurAnsquer approved these changes

2024-03-12 08:49 UTC, ArthurFlag submitted a review, later dismissed
Let's rebase on main please, the review contains incorrect changes (I think) :)

2024-03-13 08:51 UTC, ArthurFlag commented on docs/products/cassandra/howto/manage-cross-cluster-replication.md
> +You\'ve added extra disk storage space for your CCR-enabled service and
```suggestion
You've added extra disk storage space for your CCR-enabled service and
```

2024-03-13 08:52 UTC, ArthurFlag commented on docs/products/cassandra/howto/manage-cross-cluster-replication.md
> +You\'ve set up the consistency level for your service. Now operations on
```suggestion
You've set up the consistency level for your service. Now operations on
```

2024-06-28 10:02 UTC, closed without merging