add(clickhouse): local on-disk cache for remote files
aiven/aiven-docs pull request #609
Opened 2024-12-18 10:40 UTC by wojcik-dorota

## Describe your changes

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](styleguide.md).
- [ ] My links start with `/docs/`.

2024-12-18 16:51 UTC, joelynch requested changes
one small change.

2024-12-18 16:51 UTC, joelynch commented on docs/products/clickhouse/howto/local-cache-tiered-storage.md
> +improved query performance, reduced latency, and lower costs.
> lower costs

I think we should drop this.

2024-12-19 09:32 UTC, joelynch approved these changes

2024-12-19 09:32 UTC, joelynch commented
Needs approval from a code owner.

2024-12-19 13:45 UTC, ArthurFlag requested changes

2024-12-19 13:45 UTC, ArthurFlag commented on docs/products/clickhouse/howto/local-cache-tiered-storage.md
> +improved query performance and reduced latency.
```suggestion
Aiven for ClickHouse®'s tiered storage features local on-disk cache for remote files for improved query performance and reduced latency.
```

2024-12-19 15:23 UTC, ArthurFlag approved these changes

2025-01-08 14:41 UTC, joelynch commented
This has been released right @sjamgade ?  Can we merge this?

2025-01-08 15:34 UTC, sjamgade commented
@joelynch yes

2025-01-08 15:38 UTC, merged