Update: Dragonfly GA limitations
aiven/aiven-docs pull request #87
Opened 2024-02-23 11:44 UTC by harshini-rangaswamy

## Describe your changes
Updated Dragonfly documentation to include GA phase limitations:  Users, ACLs, and service configurations won’t auto-migrate from Redis to Dragonfly. 

[MA-2397](https://aiven.atlassian.net/browse/MA-2397)

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-03-05 14:17 UTC, safa-topal requested changes
Lgtm overall, left a comment on one statement which not correct yet but will be later. Also a nitpick.

2024-03-05 15:09 UTC, safa-topal approved these changes
Lgtm

2024-03-05 15:29 UTC, hoang-vo commented on docs/products/dragonfly/howto/migrate-aiven-redis-df-console.md
> +specific settings, you must manually apply these settings to Dragonfly. Automatic
same here

2024-03-10 02:39 UTC, harshini-rangaswamy commented
> we probably need to exclude ACL on DF

Updated content to remove ACL

2024-03-19 10:07 UTC, ArthurFlag reviewed
minor formatting issue and 🚀

2024-03-19 10:07 UTC, ArthurFlag commented on static/includes/dragonfly-limitations.md
> +transfer of these custom configurations is not available during the initial phase of GA.
```suggestion
  specific settings, you must manually apply these settings to Dragonfly. Automatic
  transfer of these custom configurations is not available during the initial phase of GA.
```

2024-03-19 12:27 UTC, ArthurFlag approved these changes

2024-03-19 12:27 UTC, merged