update(platform): add ip cost warning to the service termination doc
aiven/aiven-docs pull request #89
Opened 2024-02-26 10:24 UTC by wojcik-dorota

https://aiven.atlassian.net/browse/DOC-875

## Checklist

- [ ] The first paragraph of the page is on one line.
- [ ] The other lines have a line break at 90 characters.
- [ ] I checked the output.
- [ ] I applied the [style guide](../styleguide.md).
- [ ] My links start with `/docs/`.

2024-02-27 14:35 UTC, cybermax-008 reviewed
Could we include a link to this https://aiven.io/docs/platform/howto/static-ip-addresses#platform_howto_remove_static_ip somewhere in this note to guide customers on removing static IPs?

Otherwise LGTM

2024-02-27 16:06 UTC, cybermax-008 approved these changes
Thanks for updating this help article. LGTM.

2024-02-28 16:44 UTC, ArthurFlag requested changes

2024-02-28 16:44 UTC, ArthurFlag commented on docs/platform/howto/pause-from-cli.md
> +
Let's make this a reusable component 🙌  

1. Create a file in `static/includes` that contains your note.
2. Import it in both files: `Import StaticIp from "@site/static/includes/yoursnippet.md";` 
3. Use where appropriate with `<StaticIp/>`

2024-02-29 13:21 UTC, ArthurFlag approved these changes

2024-02-29 14:19 UTC, merged