add: OpenTofu guide
aiven/aiven-docs pull request #97
Opened 2024-02-29 16:57 UTC by staceysalamon-aiven

## Describe your changes

## Checklist

- [X] The first paragraph of the page is on one line.
- [X] The other lines have a line break at 90 characters.
- [X] I checked the output.
- [X] I applied the [style guide](../styleguide.md).
- [X] My links start with `/docs/`.

2024-03-01 13:03 UTC, Serpentiel approved these changes
lgtm

2024-03-04 03:42 UTC, ArthurFlag requested changes

2024-03-04 03:42 UTC, ArthurFlag commented on docs/tools/terraform/howto/use-opentofu.md
> +
This paragraph breaks the list. I suppose it's because of the 1 space indentation for this item vs the 2 space indent for the rest of the list?

2024-03-04 13:38 UTC, ArthurFlag approved these changes

2024-03-04 16:00 UTC, merged